name: build

on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Fetch value from URL
        id: fetch-url
        run: |
          VERSION=$(curl -s https://appversion.115.com/1/web/1.0/api/getMultiVer | jq '.data["Linux-115chrome"].version_code'  | tr -d '"')
          echo "Fetched value: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Read last value from file
        id: read-file
        run: |
          if [ -f .github/version ]; then
            LAST_VERSION=$(cat .github/version)
          else
            LAST_VERSION=""
          fi
          echo "Last version: $LAST_VERSION"
          echo "last_version=$LAST_VERSION" >> $GITHUB_OUTPUT
      - name: Check if values match
        id: check-match
        run: |
          if [ "${{ steps.fetch-url.outputs.version }}" = "${{ steps.read-file.outputs.last_version }}" ]; then
            echo "Values match, cancelling workflow"
            echo "should_cancel=true" >> $GITHUB_OUTPUT
          else
            echo "Values differ, proceeding with workflow"
            echo "should_cancel=false" >> $GITHUB_OUTPUT
          fi
      - name: Cancel workflow if matched
        if: steps.check-match.outputs.should_cancel == 'true'
        run: exit 1
      - name: Save version
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .github/version
          git commit -m "Update version.txt via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Release and push (master branch)
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'master' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/dream10201/115docker:latest
            docker.io/xiuxiu10201/115:latest

      - name: Release and push (non-master branch)
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name != 'master' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/dream10201/115docker:dev
            docker.io/xiuxiu10201/115:dev
